### ISSUE TITLE
[Error] SSL 인증서 갱신 안됨

### ISSUE THREAD

**Issue by DNATUNA** [prography/6th-team4-node#50]
## 내용
- SSL 인증서 갱신이 안돼요 ㅠ 확인해주세요!
![image](https://user-images.githubusercontent.com/28949165/95197988-65c9ee00-0815-11eb-83b5-0325d948c0b0.png)

**Comment by geusan** [comment]
Elastic beantalk를 쓴다면 acm을 이용하면 어떨까요

**Comment by DNATUNA** [comment]
> Elastic beantalk를 쓴다면 acm을 이용하면 어떨까요


@geusan  아쉽게도 EC2를 쓰고 있어요 ㅠ

**Comment by geusan** [comment]
> @geusan 아쉽게도 EC2를 쓰고 있어요 ㅠ

그렇다면 ㅜㅜ 매번 인증서 갱신을 어렵게...

**Comment by wwlee94** [comment]
인증서 갱신 해결 했습니다 ..!
